name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What problem are you trying to solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I could also...
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific scenarios where this would be useful
      placeholder: |
        Example 1: When debugging React components...
        Example 2: When working with async code...
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Show how you'd use this feature (code examples, workflows, etc.)
      placeholder: |
        User: "Set a conditional breakpoint that..."
        AI: "Done! The breakpoint will trigger when..."
      render: text
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Critical - I can't use Pointbreak without this
        - High - This would significantly improve my workflow
        - Medium - Nice to have
        - Low - Just an idea
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Debugging functionality (new debugging capabilities)
        - AI interaction (how AI uses Pointbreak)
        - Performance improvement
        - Developer experience
        - Documentation
        - Integration (with other tools)
        - Other
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that would help us understand your request
      placeholder: Screenshots, links to similar features, etc.
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: I have clearly described the problem this would solve
          required: true
        - label: I have provided specific use cases or examples
          required: true
